# Generated by Django 6.0.5 on 2026-05-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('fees_details', models.FloatField(default=20000)),
            ],
        ),
    ]
