# Generated by Django 6.0.5 on 2026-05-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_trainer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
        migrations.AlterModelTable(
            name='trainer',
            table='Trainer',
        ),
    ]
